### ISSUE TITLE
Problema con reflejo

### ISSUE THREAD

**Issue by Gianfranco26** [widelyresearch/programacion-creativa#121]
nico, intento hacer la ellipse que le aplique el constraint se refleje en el extremo inferior sin pasar la mitad pero el método que me dijiste que usara no lo entiendo o me sale que no esta declarado.
Intente aplicar un costraint en la ellipse inferior y que solo siguiera el movimiento inverso del mouse pero tampoco resulta.

¿Como me dijiste que se hace?
Este es el código de la Clase.

`class Clase{
  float x;
  float y;
  float mx;

  Clase(){
    x=100;
    y=100;
  }

  void real(int a){
    noFill();
    mx= constrain(a,0,height/2);
    stroke(0);
    ellipse(mouseX,mx,x,y);

    if(key=='a'){
      x=x+1;
      y=y+1;
      } if(key=='s'){
        x=x+0;
        y=y+0;
        } if(key=='d'){
          x=x-1;
          y=y-1;
        }
      }

      void espejo(Clase c){
      noFill();
      stroke(0);
      ellipse(c.x,-c.y,x,y);
      }
    }`

**Comment by nicotron** [comment]
Lo veo mañana y te comento

**Comment by nicotron** [comment]
La posición del espejo debe ser opuesta en Y pero desde la mitad del canvas, entonces las variables del objeto tienen que ser con translate desde la mitad del canvas
