### ISSUE TITLE
Duda sobre GitHub

### ISSUE THREAD

**Issue by Juaneccle** [widelyresearch/programacion-creativa#36]
Hola! 
Quería saber si es posible que alguien sin querer este comitiando cosas desde su github en mi nombre... como si alguien tuviera su abierto su github con mi cuenta iniciada. Estuve leyendo un poco sobre cómo arreglar los problemas que tengo con github y al parecer es un tema de vinculación con la cuenta.

Abro esta discusión porque se están haciendo pull requests de trabajos que son míos, pero de las primeras clases, los mismos que intente subir (pero sin exito) desde otro computador. Si alguien sabe de este asunto o le paso algo parecido avísenme por favor.

**Comment by nicotron** [comment]
@Juaneccle la única forma en que eso pueda ser, es que hay otro computador en donde está tanto GitHub Desktop y GitHub online conectados con tu cuenta.  
Debes ver en los computadores de tus compañeros quién te dejó intentar hacer un pull request en el pasado.  
Otro camino es que cambies tu password, así los pull request pedirán acceso y no podrán.
